# permissions for end users to view kubernetesapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-app-operator
    app.kubernetes.io/managed-by: kustomize
  name: kubernetesapp-viewer-role
rules:
- apiGroups:
  - webapp.example.com
  resources:
  - kubernetesapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.example.com
  resources:
  - kubernetesapps/status
  verbs:
  - get
