apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubernetesapps.webapp.example.com
spec:
  group: webapp.example.com
  names:
    kind: KubernetesApp
    listKind: KubernetesAppList
    plural: kubernetesapps
    singular: kubernetesapp
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                image:
                  type: string
                port:
                  type: integer
